#!/bin/bash
pkill -f "dzen2 -p -title-name status_bar"
length=600
height=14
font="-lucy-tewi2a-medium-r-normal--11-90-75-75-p-58-iso10646-1"

bg=$(cat ~/.Xresources |grep -i background |tail -c 8)
fg=$(cat ~/.Xresources |grep -i foreground |tail -c 8)
fg2=$(cat ~/.Xresources |grep -i color7 |tail -c 8)
red=$(cat ~/.Xresources |grep -i color1 |tail -c 8)
darkred=$(cat ~/.Xresources |grep -i color9: |tail -c 8)
yellow=$(cat ~/.Xresources |grep -i color3 |tail -c 8)
blue=$(cat ~/.Xresources |grep -i color4 |tail -c 8)
green=$(cat ~/.Xresources |grep -i color2 |tail -c 8)
magenta=$(cat ~/.Xresources |grep -i color5 |tail -c 8)
black=$(cat ~/.Xresources |grep -i color0 |tail -c 8)

key() {
	skb 1
}

load() {
    mem=$(free -m|awk 'NR==2 {print $3}')
    cpu=$(bc <<< $(ps -eo pcpu |grep -vE '^\s*(0.0|%CPU)' |sed -n '1h;$!H;$g;s/\n/ +/gp'))
    echo -ne "^p(_RIGHT)^p(-320)^fg($blue)⭦ ^fg($fg)$mem^fg($yellow)  ⭥ ^fg($fg)$cpu\r"
}

clock() {
    timea=$(date +'%a. %d %h.')
    timeb=$(date +'%H:%M:%S')
    echo "^p(_RIGHT)^p(-140)^fg($magenta)⭧ ^fg($fg)$timea ^fg($fg2)$timeb"

}

#Vil (){
#	#ONF=$(amixer get Master | awk '/Front\ Left:/ {print $7}' | tr -d '[]')
#	ViL=$(amixer get Master | egrep -o "[0-9]+%" | tr -d '%')
#    #ViL=$(pulseaudio-ctl | grep "Volume level" | cut -d":" -f 2 | grep -Eo "[0-9]+ %" | tr -d ' %')
#	echo -n "^p(_RIGHT)^p(-400)^fg($COLOR_ICON)^i($ICONPATH/vol1.xbm)^fg()" $(echo $ViL | gdbar -fg $fg -bg $fg2 -h 7 -w 40 -s o -nonl)
#	return
#}


volume() {
    sound=$(amixer get Master | sed -n 's/.*\[\([a-z]\+\)\]$/\1/p')
    vol=$(echo "`amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p'`/10" | bc)
    on=$(eval printf %${vol}s | sed 's/\s/━/g')
    off=$(eval printf %$(echo "10 - $vol" | bc)s | sed 's/\s/━/g')
    if [ "$sound" = "off" ]; then
        echo -ne "^p(_RIGHT)^p(-230)^fg($green)◂⋑ ^fg($red)$on^fg($black)$off\r"
    else
        echo -ne "^p(_RIGHT)^p(-230)^fg($green)◂⋑ ^fg($fg)$on^fg($black)$off\r"
    fi
}

while true; do
#    key
    volume
    load
    clock
    sleep 0.1
done |
dzen2 -p -title-name status_bar -fn $font -bg $bg -ta l -geometry ${length}x$height+766+0 -e 'button1=exec:urxvt' 
