#! /bin/sh

sudo sysctl -p &
sh ~/.fehbg &
compton &
sxhkd &
sh ~/bin/polybar.sh &

bspc monitor -d term code web chat music 6 7 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop="^3"
bspc rule -a Atom desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a TelegramDesktop desktop='^4'

bspc config normal_border_color "#1E2F4A"
bspc config focused_border_color "#53B0EE"
bspc config presel_feedback_color "#02583f"
